"""Configuration for the Pico-side UART-homing and one-axis DMX runtime firmware."""

# DMX input
DMX_PIN = 29
DMX_SM_ID = 4
DMX_START_CHANNEL = 1
DMX_CHANNEL_COUNT = 8
DMX_LOSS_TIMEOUT_MS = 400

# DMX v1 mapping
POSITION_MSB_CHANNEL = 1
POSITION_LSB_CHANNEL = 2
RUN_CURRENT_CHANNEL = 3
HOLD_CURRENT_CHANNEL = 4
MAX_SPEED_CHANNEL = 5
ACCELERATION_CHANNEL = 6
ENABLE_CHANNEL = 7
ENABLE_THRESHOLD = 128

# Step/dir trials for the active hardware
STEP_DIR_TRIALS = (
    (2, 3),
    (3, 2),
)
HOME_DIRECTION_TRIALS = (
    -1,
    1,
)

# Optional external DIAG debug input. It is not required for MVP homing.
DIAG_PIN = 9
DIAG_ACTIVE_LEVEL = 1

# TMC2209 UART
UART_ID = 0
UART_TX_PIN = 0
UART_RX_PIN = 1
UART_BAUDRATE = 230400
TMC_ADDRESS = 0

# EN is hardwired low on this hardware, so driver on/off must go through UART.
EN_PIN = None
DRIVER_ENABLE_TOFF = 4

# PIO stepping
PIO_STEP_SM_ID = 0
PIO_COUNTER_SM_ID = 1
PIO_STEP_FREQUENCY = 5_000_000
PIO_COUNTER_FREQUENCY = 125_000_000

# Driver defaults
MICROSTEP_MODE = 16
DEFAULT_RUN_CURRENT = 24
DEFAULT_HOLD_CURRENT = 12
CURRENT_HOLD_DELAY = 8

# UART-only homing
HOME_SPEED_TRIALS_1_8_HZ = (
    400,
)
HOME_MIN_FREQ_1_8_HZ = 300
HOME_MAX_FREQ_1_8_HZ = 1200
HOME_RETRACT_STEPS = 128
HOME_RETRACT_SPEED_HZ = 350
HOME_RELEASE_STEPS = 96
HOME_RELEASE_SPEED_HZ = 350
HOME_MAX_STEPS = 4800
HOME_MIN_TRAVEL_STEPS = 1000
HOME_POLL_MS = 5
HOME_STARTUP_SG_SAMPLES = 12
HOME_MIN_STALL_STEPS = 96
HOME_UART_THRESHOLD_RATIO = 0.30
HOME_UART_THRESHOLD_MIN = 4
HOME_UART_THRESHOLD_MAX = 16
HOME_UART_CONFIRM_POLLS = 2
HOME_SETTLE_MS = 150
HOME_TIMEOUT_MARGIN_MS = 1200
HOME_COOLSTEP_THRESHOLD = 3200

# Runtime motion limits
RUNTIME_POSITION_ONLY_MODE = True
RUNTIME_DEFAULT_TARGET_U16 = 32768
RUNTIME_DEFAULT_MAX_SPEED_HZ = 900
RUNTIME_DEFAULT_ACCEL_STEPS_S2 = 2200
RUNTIME_MIN_SPEED_HZ = 120
RUNTIME_MAX_SPEED_HZ = 1400
RUNTIME_MIN_ACCEL_STEPS_S2 = 300
RUNTIME_MAX_ACCEL_STEPS_S2 = 5000
RUNTIME_CONTROL_SLEEP_MS = 2
RUNTIME_MAX_CHUNK_STEPS = 10
RUNTIME_MIN_CHUNK_SPEED_HZ = 120
RUNTIME_DEFAULT_ENABLED = True

# Result / status output
RESULT_FILE = "homing_result.json"
STATUS_FILE = "controller_status.json"
STATUS_INTERVAL_MS = 500
PRINT_INTERVAL_MS = 500
DEBUG_LOGGING = False

# Verification / bring-up controls
RUN_RUNTIME_AFTER_HOMING = True
RUNTIME_EXIT_AFTER_MS = 0
